(voice_localdir_multisyn-rpx)
(set! myutt (SayText "Gad, do I remember it."))
(utt.save.wave myutt "arctic_b0001.wav" 'riff)
(set! myutt (SayText "I can see that knife now."))
(utt.save.wave myutt "arctic_b0003.wav" 'riff)
(set! myutt (SayText "His slim fingers closed like steel about Philip's."))
(utt.save.wave myutt "arctic_b0005.wav" 'riff)
(set! myutt (SayText "He seized Gregson by the arm and led him to the door."))
(utt.save.wave myutt "arctic_b0006.wav" 'riff)
(set! myutt (SayText "Burke himself had criticized it because of the smile."))
(utt.save.wave myutt "arctic_b0008.wav" 'riff)
(set! myutt (SayText "I'd say there was going to be a glorious scrap."))
(utt.save.wave myutt "arctic_b0009.wav" 'riff)
(set! myutt (SayText "He turned the map to Gregson, pointing with his finger."))
(utt.save.wave myutt "arctic_b0010.wav" 'riff)
(set! myutt (SayText "If you decide to eat here, just be aware it is going to take about 2 hours from beginning to end."))
(utt.save.wave myutt "yelp_000001.wav" 'riff)
(set! myutt (SayText "The food is good, but it takes a very long time to come out." ))
(utt.save.wave myutt "yelp_000004.wav" 'riff)
(set! myutt (SayText "Family diner."))
(utt.save.wave myutt "yelp_000099.wav" 'riff)
(set! myutt (SayText "Also has a menu with breakfast served all day long."))
(utt.save.wave myutt "yelp_000122.wav" 'riff)
(set! myutt (SayText "they'll modify the menu to suit your taste!"))
(utt.save.wave myutt "yelp_000699.wav" 'riff)
(set! myutt (SayText "My absolute favorite cafe in the city."))
(utt.save.wave myutt "yelp_000880.wav" 'riff)
(set! myutt (SayText "The cheese was good, but none of the other toppings added much flavor."))
(utt.save.wave myutt "yelp_000960.wav" 'riff)
(set! myutt (SayText "You are not going to order and get out of there in five minutes even though it is called express."))
(utt.save.wave myutt "yelp_001081.wav" 'riff)
(set! myutt (SayText "As a healthy alternative to fast food in the area, it is worth the wait."))
(utt.save.wave myutt "yelp_001082.wav" 'riff)
(set! myutt (SayText "Oh and try the bubble tea."))
(utt.save.wave myutt "yelp_001083.wav" 'riff)
(set! myutt (SayText "That's not right."))
(utt.save.wave myutt "everyday_0001.wav" 'riff)
(set! myutt (SayText "It depends on the weather."))
(utt.save.wave myutt "everyday_0002.wav" 'riff)
(set! myutt (SayText "Nice to meet you."))
(utt.save.wave myutt "everyday_0003.wav" 'riff)
(set! myutt (SayText "I am sorry for the mess, I wasn't expecting anyone today."))
(utt.save.wave myutt "everyday_0004.wav" 'riff)
(set! myutt (SayText "I'll be with you in a moment."))
(utt.save.wave myutt "everyday_0005.wav" 'riff)
(set! myutt (SayText "Good morning, how are you?"))
(utt.save.wave myutt "everyday_0006.wav" 'riff)
(set! myutt (SayText "Do you have any plans for the weekend?"))
(utt.save.wave myutt "everyday_0007.wav" 'riff)
(set! myutt (SayText "I have football training on Saturday morning."))
(utt.save.wave myutt "everyday_0008.wav" 'riff)
(set! myutt (SayText "Do you want to go for lunch?"))
(utt.save.wave myutt "everyday_0009.wav" 'riff)
(set! myutt (SayText "The clocks changed last week and you can really see the stretch in the evenings now."))
(utt.save.wave myutt "everyday_0010.wav" 'riff)